---
- name: Deploy packetloss
  hosts: packetloss

  tasks:
    - name: Copiar configuração do Nginx
      ansible.builtin.copy:
        src: files/09-packetloss.com.br.conf
        dest: /etc/nginx/sites.d/09-packetloss.com.br.conf
        owner: root
        group: root
        mode: "0644"
      become: true
      notify: Recarregar Nginx

    - name: Copiar unit do systemd (app)
      ansible.builtin.copy:
        src: "files/packetloss.service"
        dest: /etc/systemd/system/packetloss.service
        owner: root
        group: root
        mode: "0644"
      become: true
      notify: Recarregar systemd

    - name: Copiar unit do systemd (ranked service)
      ansible.builtin.copy:
        src: "files/packetloss-ranked.service"
        dest: /etc/systemd/system/packetloss-ranked.service
        owner: root
        group: root
        mode: "0644"
      become: true
      notify: Recarregar systemd

    - name: Copiar unit do systemd (ranked timer)
      ansible.builtin.copy:
        src: "files/packetloss-ranked.timer"
        dest: /etc/systemd/system/packetloss-ranked.timer
        owner: root
        group: root
        mode: "0644"
      become: true
      notify: Recarregar systemd

    - name: Habilitar e iniciar timer rankeada
      ansible.builtin.systemd:
        name: packetloss-ranked.timer
        enabled: true
        state: started
        daemon_reload: true
      become: true

  handlers:
    - name: Recarregar Nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: true

    - name: Recarregar systemd
      ansible.builtin.systemd:
        daemon_reload: true
      become: true
